services:
  # Backend API Server
  backend:
    # Uncomment build section for local development
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: lucimstar/unlocked-backend:1.2
    container_name: unlocked-backend
    restart: unless-stopped
    environment:
      NODE_ENV: production
      JWT_SECRET: ${JWT_SECRET:-your-super-secret-jwt-key-change-this-in-production}
      PORT: 3001
      CORS_ORIGIN: ${FRONTEND_URL:-http://localhost}
    volumes:
      # Mount SQLite database directory
      - ./backend/prisma:/app/prisma
      - sqlite_data:/app/data
    ports:
      - "${BACKEND_PORT:-3001}:3001"
    networks:
      - unlocked-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3001/api/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    security_opt:
      - no-new-privileges:true

  # Frontend React Application
  frontend:
    # Uncomment build section for local development
    build:
      context: .
      dockerfile: Dockerfile.frontend
    image: lucimstar/unlocked:1.2
    container_name: unlocked-frontend
    restart: unless-stopped
    ports:
      - "${FRONTEND_PORT:-80}:80"
    networks:
      - unlocked-network
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    security_opt:
      - no-new-privileges:true

  # Redis Cache (Optional)
  redis:
    image: redis:7-alpine
    container_name: unlocked-redis
    restart: unless-stopped
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD:-redis_password}
    volumes:
      - redis_data:/data
    ports:
      - "${REDIS_PORT:-6379}:6379"
    networks:
      - unlocked-network
    healthcheck:
      test: ["CMD-SHELL", "redis-cli --no-auth-warning -a ${REDIS_PASSWORD:-redis_password} ping | grep PONG"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    security_opt:
      - no-new-privileges:true

networks:
  unlocked-network:
    driver: bridge
    name: unlocked-network

volumes:
  sqlite_data:
    driver: local
    name: unlocked-sqlite-data
  redis_data:
    driver: local
    name: unlocked-redis-data
